# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyagent" do
  version "0.1.8"

  on_macos do
    on_intel do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_amd64.tar.gz"
      sha256 "315099c05d5830a9a2bcc0ffbd7e04ec4651f20f33307d9dad16928679b219ba"
    end
    on_arm do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_arm64.tar.gz"
      sha256 "c7cadf5cce11ba698891b757c3d27e7eb625eba29b69946708a19f36ef3da391"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_amd64.tar.gz"
      sha256 "fd26c8fffe39095f7651cd65482eea93d043efafe6826dfd5aaeb1d3c3a09abd"
    end
    on_arm do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_arm64.tar.gz"
      sha256 "7a3ee6cce5ec4995babd9d7b86ca31e924af1f68ef38d56c98bc5b67900cd635"
    end
  end

  name "lazyagent"
  desc "Observe your ai agents and sessions from the terminal"
  homepage "https://github.com/chojs23/lazyagent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyagent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyagent"]
    end
  end

  # No zap stanza required

end
