# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyagent" do
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_amd64.tar.gz"
      sha256 "7fcb315c8789f9435e1b5c6a4b9fa81a7e65e0207f520bf080e5ec56705592f5"
    end
    on_arm do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_arm64.tar.gz"
      sha256 "c4449080917b4f772757bd3665bde52c0b208f0da18c45149b35a72c03c2b4a5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_amd64.tar.gz"
      sha256 "29b73dac3a157554eb21f682df30d7e008aec37b97e58baa17b8c67adb4bb85f"
    end
    on_arm do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_arm64.tar.gz"
      sha256 "6c7997ece9cb0ae63875c4de630c6f1e090300729c0591ed5222cd562ff02a01"
    end
  end

  name "lazyagent"
  desc "Observe your ai agents and sessions from the terminal"
  homepage "https://github.com/chojs23/lazyagent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyagent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyagent"]
    end
  end

  # No zap stanza required

end
