# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyagent" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_amd64.tar.gz"
      sha256 "9de68f12f563f320a84d378b911d299b11ad6682edf27c6125b3fc5b85dbe946"
    end
    on_arm do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_darwin_arm64.tar.gz"
      sha256 "dba5f1a70ed36d1c47c93373a72cde4d0fb49ce8e8ec47b43cb82fa3bff3419b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_amd64.tar.gz"
      sha256 "53833d41fdfe8774432edd540aebf47cf1a9abc13437d24944964d234f47806c"
    end
    on_arm do
      url "https://github.com/chojs23/lazyagent/releases/download/v#{version}/lazyagent_#{version}_linux_arm64.tar.gz"
      sha256 "e062cf8e05bf8fff65bcc86aca4e1fc0fc8efef2a326ad1a37ed25072940cd81"
    end
  end

  name "lazyagent"
  desc "Observe your ai agents and sessions from the terminal"
  homepage "https://github.com/chojs23/lazyagent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyagent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazyagent"]
    end
  end

  # No zap stanza required

end
